# Generated by Django 5.0.2 on 2024-02-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
