# Generated by Django 5.0.2 on 2024-02-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredEmployee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateField(null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.department')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.job')),
            ],
        ),
    ]
