# Generated by Django 5.0.2 on 2024-02-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0004_hiredemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredemployee',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
