# Generated by Django 5.0.2 on 2024-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0005_alter_hiredemployee_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredemployee',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
